version: "3.4"
services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: progettopadovadb
    ports:
      - 5432:5432
    volumes:
      - data-postgresql:/var/lib/postgresql



  progetto_padova:
    build: .
    command: python3 manage.py progetto_padova
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: progettopadovadb
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./cache/
        target: /predict-python/cache/
      - type: bind
        source: ./scripts/
        target: /predict-python/scripts/

volumes:
  data-postgresql:
    external: true
