version: "3.4"
services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: progettopadovadb
    volumes:
      - type: bind
        source: ./db/ #TODO: your path goes here
        target: /var/lib/postgresql/data/

  progetto_padova:
    build: .
    command: python3 manage.py progetto_padova
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: progettopadovadb
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./cache/ #TODO: your path goes here
        target: /predict-python/cache/
      - type: bind
        source: ./scripts/ #TODO: your path goes here
        target: /predict-python/scripts/

